CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    created TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    priority VARCHAR(6) NOT NULL,
    CONSTRAINT tasks_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT tasks_priority_valid CHECK (priority IN ('LOW', 'NORMAL', 'URGENT'))
);
